# Spring
spring:
  application:
    name: users
  # Database
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    enabled: false

# Server
server:
  port: 8081

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
