# Spring
spring:
  application:
    name: users
  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master
  # Database
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false

# Server
server:
  port: 8081

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Logging
logging:
  level:
    org:
      springframework:
        security: DEBUG

# JMA properties
jma:
  service:
    course: COURSES
